/*

	==============================
	DATABASE EXPLORATION
	==============================
	
*/

-- Explore all objects in the database 
SELECT * FROM INFORMATION_SCHEMA.TABLES;

-- Explore all the columns in the database 
SELECT * FROM INFORMATION_SCHEMA.COLUMNS;

SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers';

/*

	==============================
	DIMENSIONS EXPLORATION
	==============================
	
*/

-- Explore all the countries our customers come from 

SELECT 
	DISTINCT country 
FROM 
	gold.dim_customers;


-- Explore all the Product categories "The major divisions"

SELECT 
	DISTINCT category,
	subcategory,
	product_name
FROM 
	gold.dim_products
ORDER BY 1, 2, 3;

/*

	==============================
	DATE EXPLORATION
	==============================
	
*/

-- Find the dates of first and last order 
-- How many years of sales are available.

SELECT 
	MIN(order_date) AS first_order_date,
	MAX(order_date) AS last_order_date,
	DATEDIFF(year, MIN(order_date), MAX(order_date)) AS order_range_in_years
FROM 
	gold.fact_sales;

-- Find the youngest and oldest customer 

SELECT 
	MIN(birthdate) AS oldest_customer,
	DATEDIFF(year, MIN(birthdate), GETDATE()) AS oldest_age,
	MAX(birthdate) AS youngest_customer,
	DATEDIFF(year, MAX(birthdate), GETDATE()) AS youngest_age
FROM 
	gold.dim_customers;

/*

	==============================
	MEASURES EXPLORATION
	==============================
	
*/

-- Find the Total Sales 

SELECT 
	SUM(sales_amount) AS total_sales
FROM 
	gold.fact_sales;

-- Find how many items are sold

SELECT 
	SUM(quantity) AS total_quantity
FROM 
	gold.fact_sales;

-- Find the average selling price 

SELECT 
	AVG(price) AS average_selling_price
FROM 
	gold.fact_sales;

-- Find the Total number of orders 

SELECT 
	COUNT(DISTINCT order_number) AS total_orders
FROM 
	gold.fact_sales;

-- Find the Total number of products

SELECT 
	COUNT(DISTINCT product_key) AS total_products 
FROM 
	gold.dim_products;

-- Find the Total number of customers 

SELECT 
	COUNT(customer_key) AS total_customers
FROM 
	gold.dim_customers;

-- Find the Total number of customers that has placed an order.

SELECT 
	COUNT(DISTINCT customer_key) AS total_customers
FROM 
	gold.fact_sales;

-- Generate a Report that shows all key metrics of the business

SELECT 
	'Total Sales' AS measure_name,
	SUM(sales_amount) AS measure_value 
FROM 
	gold.fact_sales
UNION ALL 
SELECT 
	'Total Quantity',
	SUM(quantity)
FROM	
	gold.fact_sales
UNION ALL 
SELECT 
	'Average Price',
	AVG(price) 
FROM 
	gold.fact_sales
UNION ALL 
SELECT 
	'Total Nr Orders',
	COUNT(DISTINCT order_number)
FROM 
	gold.fact_sales
UNION ALL 
SELECT 
	'Total Nr Products',
	COUNT(product_name)
FROM
	gold.dim_products
UNION ALL 
SELECT 
	'Total Nr Customers',
	COUNT(customer_key)
FROM
	gold.dim_customers;

/*

	==============================
	MAGNITUDE ANALYSIS
	==============================
	
*/

-- Find the total customers by countries 

SELECT 
	country,
	COUNT(customer_key) AS total_customers
FROM 
	gold.dim_customers 
GROUP BY country
ORDER BY total_customers DESC;

-- Find the total customers by gender 

SELECT 
	gender,
	COUNT(customer_key) AS total_customers
FROM 
	gold.dim_customers 
GROUP BY gender 
ORDER BY total_customers DESC;

-- Find total products by category 

SELECT 
	category,
	COUNT(product_key) AS total_products 
FROM 
	gold.dim_products 
GROUP BY category 
ORDER BY total_products DESC;

-- what is the average cost in each category?

SELECT 
	category,
	AVG(cost) AS avg_cost 
FROM 
	gold.dim_products 
GROUP BY category 
ORDER BY avg_cost DESC;

-- what is the total revenue generated for each category

SELECT 
	p.category AS category,
	SUM(f.sales_amount) AS total_revenue
FROM 
	gold.fact_sales AS f
LEFT JOIN gold.dim_products AS p 
ON f.product_key = p.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;

-- Total revenue generated by each customer

SELECT 
	c.customer_key,
	c.first_name,
	c.last_name,
	SUM(f.sales_amount) AS total_revenue
FROM 
	gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
ON c.customer_key = f.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name
ORDER BY total_revenue DESC;

-- What is the distribution of sold items across countries ?

SELECT 
	c.country,
	SUM(f.quantity) AS total_sold_items
FROM 
	gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC;

/*

	=====================================
	RANK ANALYSIS TOP-N & BOTTOM-N 
	=====================================
	
*/

-- Which 5 products generate the highest revenue.

SELECT TOP 5
	p.product_name,
	SUM(f.sales_amount) total_revenue
FROM 
	gold.fact_sales AS f
LEFT JOIN gold.dim_products AS p
ON f.product_key = p.product_key 
GROUP BY p.product_name
ORDER BY total_revenue DESC;

-- using window function 

SELECT 
	* 
FROM	
(
SELECT
	p.product_name,
	SUM(f.sales_amount) total_revenue,
	ROW_NUMBER() OVER(ORDER BY SUM(f.sales_amount) DESC) AS rank_product
FROM 
	gold.fact_sales AS f
LEFT JOIN gold.dim_products AS p
ON f.product_key = p.product_key 
GROUP BY p.product_name
) AS t
WHERE rank_product <= 5;

-- find the top 10 customers who have generated the highest revenue 

SELECT 
	* 
FROM	
(
SELECT
	c.customer_key,
	SUM(f.sales_amount) total_revenue,
	ROW_NUMBER() OVER(ORDER BY SUM(f.sales_amount) DESC) AS rank_product
FROM 
	gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
ON f.customer_key = c.customer_key 
GROUP BY c.customer_key
) AS t
WHERE rank_product <= 10;

-- the 3 customers with the least orders placed.


SELECT 
	* 
FROM	
(
SELECT
	c.customer_key,
	SUM(f.sales_amount) total_revenue,
	ROW_NUMBER() OVER(ORDER BY SUM(f.sales_amount)) AS rank_product
FROM 
	gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
ON f.customer_key = c.customer_key 
GROUP BY c.customer_key
) AS t
WHERE rank_product <= 3;

SELECT * FROM gold.dim_customers
